/* UMCUB_CONFIG_POST for host tests. */
#undef UMCUB_CFG_LOG_LEVEL
#define UMCUB_CFG_LOG_LEVEL 2
#undef UMCUB_CFG_CMD_ENABLE
#undef UMCUB_CFG_CMD_TABLE
#define UMCUB_CFG_CMD_ENABLE 1
#define UMCUB_CFG_CMD_TABLE  UMCUB_CMD("a", UMCUB_CMD_BOOT_APP) UMCUB_CMD("b", UMCUB_CMD_STAY) UMCUB_CMD("r", UMCUB_CMD_RESET) \
                             UMCUB_CMD("i", UMCUB_CMD_INFO) UMCUB_CMD("hello", UMCUB_CMD_USER(7)) \
                             UMCUB_CMD_INSPECT_DEFAULTS
#undef UMCUB_CFG_BOARD_TYPE
#undef UMCUB_CFG_BOARD_REV
#define UMCUB_CFG_BOARD_TYPE 0x55AA0001
#define UMCUB_CFG_BOARD_REV  3
#undef UMCUB_CFG_READBACK
#define UMCUB_CFG_READBACK 1
