/* UMCUB_CONFIG_POST for test_link.c: umcub link in ADDRESSED mode. */
#undef UMCUB_CFG_LOG_LEVEL
#define UMCUB_CFG_LOG_LEVEL 2
#undef UMCUB_CFG_UART_LINK
#define UMCUB_CFG_UART_LINK UMCUB_LINK_ADDRESSED
#undef UMCUB_CFG_CMD_ENABLE
#undef UMCUB_CFG_CMD_TABLE
#define UMCUB_CFG_CMD_ENABLE 1
#define UMCUB_CFG_CMD_TABLE  UMCUB_CMD("i", UMCUB_CMD_INFO)
