/* UMCUB_CONFIG_POST for test_board.c: board drivers + board transport only. */
#undef UMCUB_CFG_LOG_LEVEL
#define UMCUB_CFG_LOG_LEVEL 2
#undef UMCUB_CFG_TRANSPORT_UART
#define UMCUB_CFG_TRANSPORT_UART 0
#undef UMCUB_CFG_TRANSPORT_USB_CDC
#define UMCUB_CFG_TRANSPORT_USB_CDC 0
#undef UMCUB_CFG_TRANSPORT_USB_DFU
#define UMCUB_CFG_TRANSPORT_USB_DFU 0

#undef UMCUB_CFG_TRANSPORT_CAN
#define UMCUB_CFG_TRANSPORT_CAN 1
#undef UMCUB_CFG_CAN_FD
#define UMCUB_CFG_CAN_FD 1
#define UMCUB_CFG_CAN_DRIVER UMCUB_DRIVER_BOARD     /* e.g. MCP2518FD on SPI */

#undef UMCUB_CFG_TRANSPORT_ETH
#define UMCUB_CFG_TRANSPORT_ETH 1
#undef UMCUB_CFG_ETH_RMII_PINS
#define UMCUB_CFG_ETH_DRIVER UMCUB_DRIVER_BOARD     /* e.g. ENC28J60 on SPI */

#define UMCUB_CFG_TRANSPORT_USER 1                  /* e.g. W5500 UDP socket */
#define UMCUB_CFG_PROTO_USER 1                      /* board protocol next to SMP */

#undef UMCUB_CFG_CMD_ENABLE
#undef UMCUB_CFG_CMD_TABLE
#define UMCUB_CFG_CMD_ENABLE 1
#define UMCUB_CFG_CMD_TABLE  UMCUB_CMD("hello", UMCUB_CMD_USER(1))
