/* Build-matrix overlay (UMCUB_CONFIG_POST): UART + CAN-FD in loopback. */
#undef UMCUB_CFG_TRANSPORT_USB_CDC
#undef UMCUB_CFG_TRANSPORT_USB_DFU
#undef UMCUB_CFG_TRANSPORT_ETH
#undef UMCUB_CFG_TRANSPORT_CAN
#define UMCUB_CFG_TRANSPORT_USB_CDC 0
#define UMCUB_CFG_TRANSPORT_USB_DFU 0
#define UMCUB_CFG_TRANSPORT_ETH     0
#define UMCUB_CFG_TRANSPORT_CAN     1
#define UMCUB_CFG_CAN_FD            1
#define UMCUB_CFG_CAN_LOOPBACK      1
