/* Build-matrix overlay (UMCUB_CONFIG_POST): only the UART transport. */
#undef UMCUB_CFG_TRANSPORT_USB_CDC
#undef UMCUB_CFG_TRANSPORT_USB_DFU
#undef UMCUB_CFG_TRANSPORT_CAN
#undef UMCUB_CFG_TRANSPORT_ETH
#define UMCUB_CFG_TRANSPORT_USB_CDC 0
#define UMCUB_CFG_TRANSPORT_USB_DFU 0
#define UMCUB_CFG_TRANSPORT_CAN     0
#define UMCUB_CFG_TRANSPORT_ETH     0
