/* Overlay (POST): USB DFU as the only transport - no SMP, boot_serial not built. */
#undef UMCUB_CFG_TRANSPORT_UART
#undef UMCUB_CFG_TRANSPORT_USB_CDC
#undef UMCUB_CFG_TRANSPORT_USB_DFU
#undef UMCUB_CFG_TRANSPORT_CAN
#undef UMCUB_CFG_TRANSPORT_ETH
#define UMCUB_CFG_TRANSPORT_UART    0
#define UMCUB_CFG_TRANSPORT_USB_CDC 0
#define UMCUB_CFG_TRANSPORT_USB_DFU 1
#define UMCUB_CFG_TRANSPORT_CAN     0
#define UMCUB_CFG_TRANSPORT_ETH     0
