#!/usr/bin/env python3
"""Keys of the umcub link SECURE mode as C arrays for the bootloader.

  umcub_keys.py c --device device.pem --admin admin.pem -o umcub_link_keys.c

- device key (EC P-256, private): the bootloader's static key for the session
  key agreement (ECDH); its public half goes to the host tool;
- admin key (EC P-256): hosts sign the challenge with the private half; only
  the public half is embedded in the bootloader (a PEM with either half works).

  umcub_keys.py enc-c --device device.pem -o enc_key.c
                                  the device key as MCUboot's bootutil_enc_key
                                  (PKCS#8) for encrypted images
  umcub_keys.py pub key.pem       public key, hex (X || Y)
  umcub_keys.py host-c --device device.pem --admin admin.pem -o keys.c
                                  the host side (admin private, device public),
                                  for C host tools and tests
"""
import argparse
import sys
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ec


def load(path):
    data = Path(path).read_bytes()
    try:
        key = serialization.load_pem_private_key(data, password=None)
    except (ValueError, TypeError):
        key = serialization.load_pem_public_key(data)
    if not isinstance(key, (ec.EllipticCurvePrivateKey, ec.EllipticCurvePublicKey)) or \
            key.curve.name != "secp256r1":
        sys.exit(f"{path}: not an EC P-256 key")
    return key


def raw_pub(key):
    pub = key.public_key() if isinstance(key, ec.EllipticCurvePrivateKey) else key
    n = pub.public_numbers()
    return n.x.to_bytes(32, "big") + n.y.to_bytes(32, "big")


def c_array(name, data):
    rows = [", ".join(f"0x{b:02x}" for b in data[i:i + 12]) for i in range(0, len(data), 12)]
    return f"const uint8_t {name}[{len(data)}] = {{\n    " + ",\n    ".join(rows) + ",\n};\n"


def write_if_changed(path, text):
    out = Path(path)
    if not out.exists() or out.read_text() != text:
        out.write_text(text)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    c = sub.add_parser("c")
    c.add_argument("--device", required=True)
    c.add_argument("--admin", required=True)
    c.add_argument("-o", "--output", required=True)
    h = sub.add_parser("host-c")
    h.add_argument("--device", required=True)
    h.add_argument("--admin", required=True)
    h.add_argument("-o", "--output", required=True)
    e = sub.add_parser("enc-c")
    e.add_argument("--device", required=True)
    e.add_argument("-o", "--output", required=True)
    p = sub.add_parser("pub")
    p.add_argument("key")
    a = ap.parse_args()

    if a.cmd == "pub":
        print(raw_pub(load(a.key)).hex())
        return
    if a.cmd == "host-c":
        adm = load(a.admin)
        if not isinstance(adm, ec.EllipticCurvePrivateKey):
            sys.exit(f"{a.admin}: the host side needs the private admin key")
        write_if_changed(a.output,
                         "/* Generated by tools/umcub_keys.py - umcub link host side. */\n#include <stdint.h>\n\n"
                         "/* Admin private scalar (big endian): signs the challenge. */\n" +
                         c_array("umcub_link_host_admin_priv", adm.private_numbers().private_value.to_bytes(32, "big")) +
                         "\n/* Device public key (X || Y): session ECDH. */\n" +
                         c_array("umcub_link_host_device_pub", raw_pub(load(a.device))))
        return
    dev = load(a.device)
    if a.cmd == "enc-c":
        if not isinstance(dev, ec.EllipticCurvePrivateKey):
            sys.exit(f"{a.device}: the device key must be a private key")
        der = dev.private_bytes(serialization.Encoding.DER, serialization.PrivateFormat.PKCS8,
                                serialization.NoEncryption())
        write_if_changed(a.output,
                         "/* Generated by tools/umcub_keys.py - device key for encrypted images. */\n"
                         "#include <stdint.h>\n#include \"bootutil/sign_key.h\"\n\n"
                         "static " + c_array("enc_priv_key", der) +
                         f"static const unsigned int enc_priv_key_len = {len(der)};\n\n"
                         "const struct bootutil_key bootutil_enc_key = {\n"
                         "    .key = enc_priv_key,\n    .len = &enc_priv_key_len,\n};\n")
        return
    if not isinstance(dev, ec.EllipticCurvePrivateKey):
        sys.exit(f"{a.device}: the device key must be a private key")
    priv = dev.private_numbers().private_value.to_bytes(32, "big")
    text = ("/* Generated by tools/umcub_keys.py - umcub link SECURE keys. */\n#include <stdint.h>\n\n"
            "/* Device static key (private scalar, big endian): session ECDH. */\n" +
            c_array("umcub_link_device_priv", priv) +
            "\n/* Admin public key (X || Y): verifies the host's AUTH signature. */\n" +
            c_array("umcub_link_admin_pub", raw_pub(load(a.admin))))
    write_if_changed(a.output, text)


if __name__ == "__main__":
    main()
