# Application-side helpers (loaded by lib/umcub_app/CMakeLists.txt).

# Flash window of each slot, for applications that keep their own linker
# script: UMCUB_APP_FLASH_ORIGIN_<image>_<slot> / UMCUB_APP_FLASH_LENGTH_<image>_<slot>
if(NOT DEFINED UMCUB_CFG_TRAILER_RESERVE)
  set(UMCUB_CFG_TRAILER_RESERVE 8192)
endif()
foreach(_img 0 1)
  foreach(_slot 0 1)
    if(_slot EQUAL 0)
      set(_a ${UMCUB_CFG_IMG${_img}_PRIMARY_ADDR})
      set(_s ${UMCUB_CFG_IMG${_img}_PRIMARY_SIZE})
    else()
      set(_a ${UMCUB_CFG_IMG${_img}_SECONDARY_ADDR})
      set(_s ${UMCUB_CFG_IMG${_img}_SECONDARY_SIZE})
    endif()
    if(_s)
      math(EXPR _o "${_a} + ${UMCUB_CFG_IMAGE_HEADER_SIZE}" OUTPUT_FORMAT HEXADECIMAL)
      math(EXPR _l "${_s} - ${UMCUB_CFG_IMAGE_HEADER_SIZE} - ${UMCUB_CFG_TRAILER_RESERVE}" OUTPUT_FORMAT HEXADECIMAL)
      set(UMCUB_APP_FLASH_ORIGIN_${_img}_${_slot} ${_o})
      set(UMCUB_APP_FLASH_LENGTH_${_img}_${_slot} ${_l})
    endif()
  endforeach()
endforeach()

# umcub_app_linker_script(<target> [IMAGE <n>] [SLOT <0|1>] [TEMPLATE <file.ld.in>])
# Generates a linker script for the slot from the family template (or your
# own template, preprocessed with umcub_cfg.h) and links <target> with it.
function(umcub_app_linker_script target)
  cmake_parse_arguments(A "" "IMAGE;SLOT;TEMPLATE" "" ${ARGN})
  if(NOT DEFINED A_IMAGE)
    set(A_IMAGE 0)
  endif()
  if(NOT DEFINED A_SLOT)
    set(A_SLOT 0)
  endif()
  if(NOT A_TEMPLATE)
    set(A_TEMPLATE ${UMCUB_FAMILY_APP_LD})
  endif()
  set(_defs ${UMCUB_CONFIG_DEFS})
  list(APPEND UMCUB_CONFIG_DEFS UMCUB_APP_IMAGE=${A_IMAGE} UMCUB_APP_SLOT=${A_SLOT})
  set(_out "${CMAKE_CURRENT_BINARY_DIR}/${target}_img${A_IMAGE}_slot${A_SLOT}.ld")
  umcub_preprocess("${A_TEMPLATE}" "${_out}")
  set(UMCUB_CONFIG_DEFS ${_defs})
  target_link_options(${target} PRIVATE -T${_out})
  set_property(TARGET ${target} APPEND PROPERTY LINK_DEPENDS "${_out}")
endfunction()
