# Wraps `imgtool getpub --lang c` output into MCUboot's bootutil_keys[] table.
file(READ "${RAW}" _key)
file(WRITE "${OUT}" "/* Generated by umcub from the signing key - do not edit. */
#include \"bootutil/sign_key.h\"

${_key}
const struct bootutil_key bootutil_keys[] = {
    { .key = ecdsa_pub_key, .len = &ecdsa_pub_key_len },
};
const int bootutil_key_cnt = 1;
")
