# Wraps imgtool key dumps into the tables MCUboot expects:
#   MODE pub (default): `imgtool getpub --lang c` -> bootutil_keys[] (signature check)
#   MODE enc:           `imgtool getpriv`         -> bootutil_enc_key (image decryption)
file(READ "${RAW}" _key)
if(MODE STREQUAL "enc")
  file(WRITE "${OUT}" "/* Generated by umcub from the device key - do not edit. */
#include \"bootutil/sign_key.h\"

${_key}
const struct bootutil_key bootutil_enc_key = {
    .key = enc_priv_key,
    .len = &enc_priv_key_len,
};
")
else()
  file(WRITE "${OUT}" "/* Generated by umcub from the signing key - do not edit. */
#include \"bootutil/sign_key.h\"

${_key}
const struct bootutil_key bootutil_keys[] = {
    { .key = ecdsa_pub_key, .len = &ecdsa_pub_key_len },
};
const int bootutil_key_cnt = 1;
")
endif()
